# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Questionnaire-fe CI

on:
  push:
    branches: ['production']
  pull_request:
    branches: ['production']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Activate Yarn 4.9.1
        run: corepack prepare yarn@4.9.1 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint the code
        run: yarn run lint

      - name: Build the project
        run: yarn run build

      - name: Run unit tests
        run: yarn run test
